theme = "ocean-space"

[editor]
bufferline = "always"
end-of-line-diagnostics = "hint"
line-number = "relative"
popup-border = "all"
auto-pairs = false

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-progress-messages = true

#[editor.indent-guides]
#render = true

# Move lines up and down
[keys.normal]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"C-d" = ["page_cursor_half_down", "align_view_center"]
"C-u" = ["page_cursor_half_up", "align_view_center"]
